-- =====================================================================
-- V1__initial_schema.sql
-- AgendaFlow - migración inicial para Flyway
-- Ejecutar conectado a: agendaflow_db
-- Usuario recomendado: agendaflow_user
-- IDs: BIGINT GENERATED BY DEFAULT AS IDENTITY
--
-- IMPORTANTE:
-- Flyway administra la transacción de esta migración en PostgreSQL.
-- Por eso este archivo no incluye BEGIN ni COMMIT explícitos.
-- =====================================================================

-- =========================================================
-- AGENDAFLOW - ESQUEMA INICIAL
-- PostgreSQL
-- IDs: BIGINT GENERATED BY DEFAULT AS IDENTITY
-- =========================================================

CREATE SCHEMA IF NOT EXISTS agendaflow AUTHORIZATION agendaflow_user;
CREATE SCHEMA IF NOT EXISTS audit AUTHORIZATION agendaflow_user;
CREATE SCHEMA IF NOT EXISTS batch AUTHORIZATION agendaflow_user;

SET search_path TO agendaflow, public;

-- =========================================================
-- ORGANIZACIONES Y SUCURSALES
-- =========================================================

CREATE TABLE organizations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    legal_name VARCHAR(180) NOT NULL,
    trade_name VARCHAR(180),
    tax_identifier VARCHAR(50),
    organization_type VARCHAR(50),
    email VARCHAR(254),
    phone VARCHAR(30),
    website VARCHAR(255),
    address_line_1 VARCHAR(150),
    address_line_2 VARCHAR(150),
    city VARCHAR(100),
    state_code VARCHAR(10),
    postal_code VARCHAR(15),
    country_code VARCHAR(2) NOT NULL DEFAULT 'US',
    logo_url VARCHAR(500),
    timezone VARCHAR(60) NOT NULL DEFAULT 'America/New_York',
    currency_code VARCHAR(3) NOT NULL DEFAULT 'USD',
    language_code VARCHAR(10) NOT NULL DEFAULT 'en-US',
    allows_public_booking BOOLEAN NOT NULL DEFAULT TRUE,
    allows_guest_booking BOOLEAN NOT NULL DEFAULT TRUE,
    requires_appointment_confirmation BOOLEAN NOT NULL DEFAULT FALSE,
    minimum_booking_notice_minutes INTEGER NOT NULL DEFAULT 0,
    maximum_booking_days_ahead INTEGER NOT NULL DEFAULT 365,
    cancellation_notice_minutes INTEGER NOT NULL DEFAULT 0,
    status VARCHAR(30) NOT NULL DEFAULT 'ACTIVE',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMPTZ,
    CONSTRAINT chk_organization_status
        CHECK (status IN ('PENDING', 'ACTIVE', 'SUSPENDED', 'INACTIVE')),
    CONSTRAINT chk_organization_booking_notice
        CHECK (minimum_booking_notice_minutes >= 0),
    CONSTRAINT chk_organization_booking_days
        CHECK (maximum_booking_days_ahead >= 0),
    CONSTRAINT chk_organization_cancellation_notice
        CHECK (cancellation_notice_minutes >= 0)
);

CREATE UNIQUE INDEX uq_organizations_tax_identifier
    ON organizations (tax_identifier)
    WHERE tax_identifier IS NOT NULL AND deleted_at IS NULL;

CREATE TABLE branches (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT NOT NULL,
    name VARCHAR(150) NOT NULL,
    code VARCHAR(40),
    email VARCHAR(254),
    phone VARCHAR(30),
    address_line_1 VARCHAR(150),
    address_line_2 VARCHAR(150),
    city VARCHAR(100),
    state_code VARCHAR(10),
    postal_code VARCHAR(15),
    country_code VARCHAR(2) NOT NULL DEFAULT 'US',
    timezone VARCHAR(60),
    latitude NUMERIC(9,6),
    longitude NUMERIC(9,6),
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMPTZ,
    CONSTRAINT fk_branches_organization
        FOREIGN KEY (organization_id) REFERENCES organizations (id),
    CONSTRAINT uq_branch_name UNIQUE (organization_id, name),
    CONSTRAINT uq_branch_code UNIQUE (organization_id, code)
);

-- =========================================================
-- USUARIOS, MEMBRESÍAS, ROLES Y PERMISOS
-- =========================================================

CREATE TABLE app_users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(254) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    first_name VARCHAR(80) NOT NULL,
    middle_name VARCHAR(80),
    last_name VARCHAR(80) NOT NULL,
    second_last_name VARCHAR(80),
    phone VARCHAR(30),
    avatar_url VARCHAR(500),
    preferred_language VARCHAR(10) DEFAULT 'en-US',
    email_verified BOOLEAN NOT NULL DEFAULT FALSE,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    is_locked BOOLEAN NOT NULL DEFAULT FALSE,
    failed_login_attempts INTEGER NOT NULL DEFAULT 0,
    last_login_at TIMESTAMPTZ,
    password_changed_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMPTZ,
    CONSTRAINT uq_app_users_email UNIQUE (email),
    CONSTRAINT chk_failed_login_attempts CHECK (failed_login_attempts >= 0)
);

CREATE TABLE organization_memberships (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'ACTIVE',
    joined_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    invited_at TIMESTAMPTZ,
    invited_by BIGINT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_membership_organization
        FOREIGN KEY (organization_id) REFERENCES organizations (id),
    CONSTRAINT fk_membership_user
        FOREIGN KEY (user_id) REFERENCES app_users (id),
    CONSTRAINT fk_membership_invited_by
        FOREIGN KEY (invited_by) REFERENCES app_users (id),
    CONSTRAINT uq_membership UNIQUE (organization_id, user_id),
    CONSTRAINT chk_membership_status
        CHECK (status IN ('INVITED', 'ACTIVE', 'SUSPENDED', 'INACTIVE'))
);

CREATE TABLE roles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT,
    name VARCHAR(80) NOT NULL,
    description TEXT,
    is_system_role BOOLEAN NOT NULL DEFAULT FALSE,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_roles_organization
        FOREIGN KEY (organization_id) REFERENCES organizations (id)
);

CREATE UNIQUE INDEX uq_global_role_name
    ON roles (name)
    WHERE organization_id IS NULL;

CREATE UNIQUE INDEX uq_organization_role_name
    ON roles (organization_id, name)
    WHERE organization_id IS NOT NULL;

CREATE TABLE permissions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(100) NOT NULL,
    name VARCHAR(120) NOT NULL,
    description TEXT,
    module VARCHAR(80),
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_permissions_code UNIQUE (code)
);

CREATE TABLE role_permissions (
    role_id BIGINT NOT NULL,
    permission_id BIGINT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (role_id, permission_id),
    CONSTRAINT fk_role_permissions_role
        FOREIGN KEY (role_id) REFERENCES roles (id) ON DELETE CASCADE,
    CONSTRAINT fk_role_permissions_permission
        FOREIGN KEY (permission_id) REFERENCES permissions (id) ON DELETE CASCADE
);

CREATE TABLE membership_roles (
    membership_id BIGINT NOT NULL,
    role_id BIGINT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (membership_id, role_id),
    CONSTRAINT fk_membership_roles_membership
        FOREIGN KEY (membership_id) REFERENCES organization_memberships (id) ON DELETE CASCADE,
    CONSTRAINT fk_membership_roles_role
        FOREIGN KEY (role_id) REFERENCES roles (id) ON DELETE CASCADE
);

CREATE TABLE membership_branches (
    membership_id BIGINT NOT NULL,
    branch_id BIGINT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (membership_id, branch_id),
    CONSTRAINT fk_membership_branches_membership
        FOREIGN KEY (membership_id) REFERENCES organization_memberships (id) ON DELETE CASCADE,
    CONSTRAINT fk_membership_branches_branch
        FOREIGN KEY (branch_id) REFERENCES branches (id) ON DELETE CASCADE
);

-- =========================================================
-- CONTACTOS, REPRESENTANTES Y PROPIETARIOS
-- =========================================================

CREATE TABLE organization_contacts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT NOT NULL,
    user_id BIGINT,
    first_name VARCHAR(80) NOT NULL,
    middle_name VARCHAR(80),
    last_name VARCHAR(80) NOT NULL,
    second_last_name VARCHAR(80),
    job_title VARCHAR(120),
    contact_type VARCHAR(40) NOT NULL,
    email VARCHAR(254),
    phone VARCHAR(30),
    is_primary BOOLEAN NOT NULL DEFAULT FALSE,
    is_legal_representative BOOLEAN NOT NULL DEFAULT FALSE,
    is_billing_contact BOOLEAN NOT NULL DEFAULT FALSE,
    is_technical_contact BOOLEAN NOT NULL DEFAULT FALSE,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    started_at DATE,
    ended_at DATE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_org_contacts_organization
        FOREIGN KEY (organization_id) REFERENCES organizations (id),
    CONSTRAINT fk_org_contacts_user
        FOREIGN KEY (user_id) REFERENCES app_users (id),
    CONSTRAINT chk_org_contact_type
        CHECK (contact_type IN (
            'OWNER', 'CO_OWNER', 'CEO', 'PRESIDENT', 'DIRECTOR',
            'LEGAL_REPRESENTATIVE', 'ADMINISTRATIVE_CONTACT',
            'BILLING_CONTACT', 'TECHNICAL_CONTACT', 'OTHER'
        )),
    CONSTRAINT chk_org_contact_dates
        CHECK (ended_at IS NULL OR started_at IS NULL OR ended_at >= started_at)
);

CREATE UNIQUE INDEX uq_primary_organization_contact
    ON organization_contacts (organization_id)
    WHERE is_primary = TRUE AND is_active = TRUE;

CREATE TABLE organization_owners (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT NOT NULL,
    organization_contact_id BIGINT NOT NULL,
    ownership_percentage NUMERIC(5,2),
    is_beneficial_owner BOOLEAN NOT NULL DEFAULT FALSE,
    started_at DATE,
    ended_at DATE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_org_owners_organization
        FOREIGN KEY (organization_id) REFERENCES organizations (id),
    CONSTRAINT fk_org_owners_contact
        FOREIGN KEY (organization_contact_id) REFERENCES organization_contacts (id),
    CONSTRAINT uq_organization_owner
        UNIQUE (organization_id, organization_contact_id),
    CONSTRAINT chk_ownership_percentage
        CHECK (ownership_percentage IS NULL OR ownership_percentage BETWEEN 0 AND 100),
    CONSTRAINT chk_ownership_dates
        CHECK (ended_at IS NULL OR started_at IS NULL OR ended_at >= started_at)
);

-- =========================================================
-- SERVICIOS Y ESPECIALISTAS
-- =========================================================

CREATE TABLE service_categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT NOT NULL,
    name VARCHAR(120) NOT NULL,
    description TEXT,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_service_categories_organization
        FOREIGN KEY (organization_id) REFERENCES organizations (id),
    CONSTRAINT uq_service_category_name UNIQUE (organization_id, name)
);

CREATE TABLE services (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT NOT NULL,
    category_id BIGINT,
    name VARCHAR(150) NOT NULL,
    description TEXT,
    duration_minutes INTEGER NOT NULL,
    preparation_minutes INTEGER NOT NULL DEFAULT 0,
    cleanup_minutes INTEGER NOT NULL DEFAULT 0,
    price NUMERIC(12,2),
    currency_code VARCHAR(3) NOT NULL DEFAULT 'USD',
    requires_approval BOOLEAN NOT NULL DEFAULT FALSE,
    allows_online_booking BOOLEAN NOT NULL DEFAULT TRUE,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    color_code VARCHAR(20),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMPTZ,
    CONSTRAINT fk_services_organization
        FOREIGN KEY (organization_id) REFERENCES organizations (id),
    CONSTRAINT fk_services_category
        FOREIGN KEY (category_id) REFERENCES service_categories (id),
    CONSTRAINT uq_service_name UNIQUE (organization_id, name),
    CONSTRAINT chk_service_duration CHECK (duration_minutes > 0),
    CONSTRAINT chk_service_preparation CHECK (preparation_minutes >= 0),
    CONSTRAINT chk_service_cleanup CHECK (cleanup_minutes >= 0),
    CONSTRAINT chk_service_price CHECK (price IS NULL OR price >= 0)
);

CREATE TABLE branch_services (
    branch_id BIGINT NOT NULL,
    service_id BIGINT NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (branch_id, service_id),
    CONSTRAINT fk_branch_services_branch
        FOREIGN KEY (branch_id) REFERENCES branches (id) ON DELETE CASCADE,
    CONSTRAINT fk_branch_services_service
        FOREIGN KEY (service_id) REFERENCES services (id) ON DELETE CASCADE
);

CREATE TABLE specialists (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT NOT NULL,
    user_id BIGINT,
    professional_name VARCHAR(160) NOT NULL,
    specialty_name VARCHAR(150),
    biography TEXT,
    license_number VARCHAR(80),
    photo_url VARCHAR(500),
    phone VARCHAR(30),
    email VARCHAR(254),
    simultaneous_capacity INTEGER NOT NULL DEFAULT 1,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMPTZ,
    CONSTRAINT fk_specialists_organization
        FOREIGN KEY (organization_id) REFERENCES organizations (id),
    CONSTRAINT fk_specialists_user
        FOREIGN KEY (user_id) REFERENCES app_users (id),
    CONSTRAINT uq_specialist_user UNIQUE (organization_id, user_id),
    CONSTRAINT chk_specialist_capacity CHECK (simultaneous_capacity > 0)
);

CREATE TABLE specialist_branches (
    specialist_id BIGINT NOT NULL,
    branch_id BIGINT NOT NULL,
    is_primary BOOLEAN NOT NULL DEFAULT FALSE,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (specialist_id, branch_id),
    CONSTRAINT fk_specialist_branches_specialist
        FOREIGN KEY (specialist_id) REFERENCES specialists (id) ON DELETE CASCADE,
    CONSTRAINT fk_specialist_branches_branch
        FOREIGN KEY (branch_id) REFERENCES branches (id) ON DELETE CASCADE
);

CREATE TABLE specialist_services (
    specialist_id BIGINT NOT NULL,
    service_id BIGINT NOT NULL,
    custom_duration_minutes INTEGER,
    custom_price NUMERIC(12,2),
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (specialist_id, service_id),
    CONSTRAINT fk_specialist_services_specialist
        FOREIGN KEY (specialist_id) REFERENCES specialists (id) ON DELETE CASCADE,
    CONSTRAINT fk_specialist_services_service
        FOREIGN KEY (service_id) REFERENCES services (id) ON DELETE CASCADE,
    CONSTRAINT chk_specialist_custom_duration
        CHECK (custom_duration_minutes IS NULL OR custom_duration_minutes > 0),
    CONSTRAINT chk_specialist_custom_price
        CHECK (custom_price IS NULL OR custom_price >= 0)
);

-- =========================================================
-- HORARIOS Y RECURSOS
-- =========================================================

CREATE TABLE availability_schedules (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT NOT NULL,
    specialist_id BIGINT NOT NULL,
    branch_id BIGINT NOT NULL,
    day_of_week SMALLINT NOT NULL,
    start_time TIME NOT NULL,
    end_time TIME NOT NULL,
    valid_from DATE,
    valid_until DATE,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_availability_organization
        FOREIGN KEY (organization_id) REFERENCES organizations (id),
    CONSTRAINT fk_availability_specialist
        FOREIGN KEY (specialist_id) REFERENCES specialists (id),
    CONSTRAINT fk_availability_branch
        FOREIGN KEY (branch_id) REFERENCES branches (id),
    CONSTRAINT chk_availability_day CHECK (day_of_week BETWEEN 0 AND 6),
    CONSTRAINT chk_availability_time CHECK (end_time > start_time),
    CONSTRAINT chk_availability_dates
        CHECK (valid_until IS NULL OR valid_from IS NULL OR valid_until >= valid_from)
);

CREATE TABLE schedule_blocks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT NOT NULL,
    specialist_id BIGINT,
    branch_id BIGINT,
    block_type VARCHAR(30) NOT NULL,
    starts_at TIMESTAMPTZ NOT NULL,
    ends_at TIMESTAMPTZ NOT NULL,
    reason TEXT,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_by BIGINT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_schedule_blocks_organization
        FOREIGN KEY (organization_id) REFERENCES organizations (id),
    CONSTRAINT fk_schedule_blocks_specialist
        FOREIGN KEY (specialist_id) REFERENCES specialists (id),
    CONSTRAINT fk_schedule_blocks_branch
        FOREIGN KEY (branch_id) REFERENCES branches (id),
    CONSTRAINT fk_schedule_blocks_created_by
        FOREIGN KEY (created_by) REFERENCES app_users (id),
    CONSTRAINT chk_schedule_block_type
        CHECK (block_type IN (
            'BREAK', 'VACATION', 'HOLIDAY', 'SICK_LEAVE', 'PERSONAL',
            'MEETING', 'MAINTENANCE', 'OTHER'
        )),
    CONSTRAINT chk_schedule_block_range CHECK (ends_at > starts_at)
);

CREATE TABLE resources (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT NOT NULL,
    branch_id BIGINT NOT NULL,
    name VARCHAR(150) NOT NULL,
    resource_type VARCHAR(60) NOT NULL,
    description TEXT,
    capacity INTEGER NOT NULL DEFAULT 1,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_resources_organization
        FOREIGN KEY (organization_id) REFERENCES organizations (id),
    CONSTRAINT fk_resources_branch
        FOREIGN KEY (branch_id) REFERENCES branches (id),
    CONSTRAINT uq_resource_name UNIQUE (branch_id, name),
    CONSTRAINT chk_resource_capacity CHECK (capacity > 0)
);

CREATE TABLE resource_services (
    resource_id BIGINT NOT NULL,
    service_id BIGINT NOT NULL,
    is_required BOOLEAN NOT NULL DEFAULT FALSE,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (resource_id, service_id),
    CONSTRAINT fk_resource_services_resource
        FOREIGN KEY (resource_id) REFERENCES resources (id) ON DELETE CASCADE,
    CONSTRAINT fk_resource_services_service
        FOREIGN KEY (service_id) REFERENCES services (id) ON DELETE CASCADE
);

-- =========================================================
-- CLIENTES
-- =========================================================

CREATE TABLE customers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT NOT NULL,
    customer_number VARCHAR(40),
    first_name VARCHAR(80) NOT NULL,
    middle_name VARCHAR(80),
    last_name VARCHAR(80) NOT NULL,
    second_last_name VARCHAR(80),
    email VARCHAR(254),
    phone VARCHAR(30),
    alternate_phone VARCHAR(30),
    date_of_birth DATE,
    preferred_language VARCHAR(10) DEFAULT 'en-US',
    preferred_contact_method VARCHAR(20),
    address_line_1 VARCHAR(150),
    address_line_2 VARCHAR(150),
    city VARCHAR(100),
    state_code VARCHAR(10),
    postal_code VARCHAR(15),
    country_code VARCHAR(2) NOT NULL DEFAULT 'US',
    emergency_contact_name VARCHAR(160),
    emergency_contact_phone VARCHAR(30),
    emergency_contact_relationship VARCHAR(80),
    email_consent BOOLEAN NOT NULL DEFAULT FALSE,
    sms_consent BOOLEAN NOT NULL DEFAULT FALSE,
    marketing_consent BOOLEAN NOT NULL DEFAULT FALSE,
    terms_accepted_at TIMESTAMPTZ,
    privacy_policy_accepted_at TIMESTAMPTZ,
    internal_notes TEXT,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMPTZ,
    CONSTRAINT fk_customers_organization
        FOREIGN KEY (organization_id) REFERENCES organizations (id),
    CONSTRAINT uq_customer_number UNIQUE (organization_id, customer_number),
    CONSTRAINT chk_customer_contact_method
        CHECK (
            preferred_contact_method IS NULL
            OR preferred_contact_method IN ('EMAIL', 'SMS', 'PHONE', 'NONE')
        )
);

CREATE INDEX idx_customers_organization_name
    ON customers (organization_id, last_name, first_name);

CREATE INDEX idx_customers_organization_email
    ON customers (organization_id, email);

CREATE INDEX idx_customers_organization_phone
    ON customers (organization_id, phone);

-- =========================================================
-- CITAS
-- =========================================================

CREATE TABLE appointments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT NOT NULL,
    branch_id BIGINT NOT NULL,
    customer_id BIGINT NOT NULL,
    service_id BIGINT NOT NULL,
    specialist_id BIGINT NOT NULL,
    resource_id BIGINT,
    starts_at TIMESTAMPTZ NOT NULL,
    ends_at TIMESTAMPTZ NOT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'PENDING',
    origin VARCHAR(30) NOT NULL DEFAULT 'RECEPTION',
    customer_notes TEXT,
    internal_notes TEXT,
    cancellation_reason TEXT,
    cancelled_at TIMESTAMPTZ,
    cancelled_by BIGINT,
    confirmed_at TIMESTAMPTZ,
    checked_in_at TIMESTAMPTZ,
    started_service_at TIMESTAMPTZ,
    completed_at TIMESTAMPTZ,
    created_by BIGINT,
    updated_by BIGINT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMPTZ,
    CONSTRAINT fk_appointments_organization
        FOREIGN KEY (organization_id) REFERENCES organizations (id),
    CONSTRAINT fk_appointments_branch
        FOREIGN KEY (branch_id) REFERENCES branches (id),
    CONSTRAINT fk_appointments_customer
        FOREIGN KEY (customer_id) REFERENCES customers (id),
    CONSTRAINT fk_appointments_service
        FOREIGN KEY (service_id) REFERENCES services (id),
    CONSTRAINT fk_appointments_specialist
        FOREIGN KEY (specialist_id) REFERENCES specialists (id),
    CONSTRAINT fk_appointments_resource
        FOREIGN KEY (resource_id) REFERENCES resources (id),
    CONSTRAINT fk_appointments_cancelled_by
        FOREIGN KEY (cancelled_by) REFERENCES app_users (id),
    CONSTRAINT fk_appointments_created_by
        FOREIGN KEY (created_by) REFERENCES app_users (id),
    CONSTRAINT fk_appointments_updated_by
        FOREIGN KEY (updated_by) REFERENCES app_users (id),
    CONSTRAINT chk_appointment_range CHECK (ends_at > starts_at),
    CONSTRAINT chk_appointment_status
        CHECK (status IN (
            'PENDING', 'CONFIRMED', 'CHECKED_IN', 'IN_PROGRESS',
            'COMPLETED', 'CANCELLED', 'NO_SHOW', 'RESCHEDULED'
        )),
    CONSTRAINT chk_appointment_origin
        CHECK (origin IN (
            'PUBLIC_PORTAL', 'CUSTOMER_PORTAL', 'RECEPTION',
            'PHONE', 'ADMINISTRATION', 'IMPORT'
        ))
);

CREATE INDEX idx_appointments_organization_start
    ON appointments (organization_id, starts_at);

CREATE INDEX idx_appointments_branch_start
    ON appointments (branch_id, starts_at);

CREATE INDEX idx_appointments_specialist_start
    ON appointments (specialist_id, starts_at);

CREATE INDEX idx_appointments_customer_start
    ON appointments (customer_id, starts_at);

CREATE INDEX idx_appointments_status
    ON appointments (organization_id, status);

CREATE TABLE appointment_status_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    appointment_id BIGINT NOT NULL,
    previous_status VARCHAR(30),
    new_status VARCHAR(30) NOT NULL,
    changed_by BIGINT,
    change_reason TEXT,
    changed_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_appointment_history_appointment
        FOREIGN KEY (appointment_id) REFERENCES appointments (id) ON DELETE CASCADE,
    CONSTRAINT fk_appointment_history_changed_by
        FOREIGN KEY (changed_by) REFERENCES app_users (id)
);

-- =========================================================
-- LISTA DE ESPERA
-- =========================================================

CREATE TABLE waitlist_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT NOT NULL,
    customer_id BIGINT NOT NULL,
    service_id BIGINT NOT NULL,
    specialist_id BIGINT,
    branch_id BIGINT,
    preferred_date_from DATE,
    preferred_date_until DATE,
    preferred_time_from TIME,
    preferred_time_until TIME,
    status VARCHAR(30) NOT NULL DEFAULT 'PENDING',
    notes TEXT,
    expires_at TIMESTAMPTZ,
    fulfilled_appointment_id BIGINT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_waitlist_organization
        FOREIGN KEY (organization_id) REFERENCES organizations (id),
    CONSTRAINT fk_waitlist_customer
        FOREIGN KEY (customer_id) REFERENCES customers (id),
    CONSTRAINT fk_waitlist_service
        FOREIGN KEY (service_id) REFERENCES services (id),
    CONSTRAINT fk_waitlist_specialist
        FOREIGN KEY (specialist_id) REFERENCES specialists (id),
    CONSTRAINT fk_waitlist_branch
        FOREIGN KEY (branch_id) REFERENCES branches (id),
    CONSTRAINT fk_waitlist_appointment
        FOREIGN KEY (fulfilled_appointment_id) REFERENCES appointments (id),
    CONSTRAINT chk_waitlist_status
        CHECK (status IN ('PENDING', 'NOTIFIED', 'FULFILLED', 'CANCELLED', 'EXPIRED')),
    CONSTRAINT chk_waitlist_dates
        CHECK (
            preferred_date_until IS NULL
            OR preferred_date_from IS NULL
            OR preferred_date_until >= preferred_date_from
        ),
    CONSTRAINT chk_waitlist_times
        CHECK (
            preferred_time_until IS NULL
            OR preferred_time_from IS NULL
            OR preferred_time_until > preferred_time_from
        )
);

-- =========================================================
-- NOTIFICACIONES
-- =========================================================

CREATE TABLE notification_templates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT NOT NULL,
    code VARCHAR(80) NOT NULL,
    name VARCHAR(150) NOT NULL,
    notification_type VARCHAR(40) NOT NULL,
    channel VARCHAR(30) NOT NULL,
    subject_template TEXT,
    body_template TEXT NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_notification_templates_organization
        FOREIGN KEY (organization_id) REFERENCES organizations (id),
    CONSTRAINT uq_notification_template
        UNIQUE (organization_id, code, channel),
    CONSTRAINT chk_notification_template_channel
        CHECK (channel IN ('EMAIL', 'SMS', 'IN_APP', 'WHATSAPP'))
);

CREATE TABLE notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT NOT NULL,
    template_id BIGINT,
    user_id BIGINT,
    customer_id BIGINT,
    appointment_id BIGINT,
    notification_type VARCHAR(40) NOT NULL,
    channel VARCHAR(30) NOT NULL,
    recipient VARCHAR(254) NOT NULL,
    subject TEXT,
    body TEXT NOT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'PENDING',
    scheduled_at TIMESTAMPTZ,
    sent_at TIMESTAMPTZ,
    failed_at TIMESTAMPTZ,
    failure_reason TEXT,
    provider_message_id VARCHAR(255),
    retry_count INTEGER NOT NULL DEFAULT 0,
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_notifications_organization
        FOREIGN KEY (organization_id) REFERENCES organizations (id),
    CONSTRAINT fk_notifications_template
        FOREIGN KEY (template_id) REFERENCES notification_templates (id),
    CONSTRAINT fk_notifications_user
        FOREIGN KEY (user_id) REFERENCES app_users (id),
    CONSTRAINT fk_notifications_customer
        FOREIGN KEY (customer_id) REFERENCES customers (id),
    CONSTRAINT fk_notifications_appointment
        FOREIGN KEY (appointment_id) REFERENCES appointments (id),
    CONSTRAINT chk_notifications_channel
        CHECK (channel IN ('EMAIL', 'SMS', 'IN_APP', 'WHATSAPP')),
    CONSTRAINT chk_notifications_status
        CHECK (status IN ('PENDING', 'PROCESSING', 'SENT', 'FAILED', 'CANCELLED')),
    CONSTRAINT chk_notifications_retry CHECK (retry_count >= 0)
);

CREATE INDEX idx_notifications_pending
    ON notifications (status, scheduled_at)
    WHERE status = 'PENDING';

-- =========================================================
-- AUDITORÍA
-- =========================================================

CREATE TABLE audit.audit_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT,
    user_id BIGINT,
    table_schema VARCHAR(100),
    table_name VARCHAR(100) NOT NULL,
    record_id BIGINT,
    action VARCHAR(30) NOT NULL,
    old_values JSONB,
    new_values JSONB,
    changed_fields JSONB,
    ip_address INET,
    user_agent TEXT,
    request_id VARCHAR(100),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_audit_organization
        FOREIGN KEY (organization_id) REFERENCES agendaflow.organizations (id),
    CONSTRAINT fk_audit_user
        FOREIGN KEY (user_id) REFERENCES agendaflow.app_users (id),
    CONSTRAINT chk_audit_action
        CHECK (action IN ('INSERT', 'UPDATE', 'DELETE', 'LOGIN', 'LOGOUT', 'EXPORT', 'ACCESS'))
);

CREATE INDEX idx_audit_events_organization_created
    ON audit.audit_events (organization_id, created_at DESC);

CREATE INDEX idx_audit_events_record
    ON audit.audit_events (table_name, record_id);

CREATE INDEX idx_audit_events_user_created
    ON audit.audit_events (user_id, created_at DESC);

-- =========================================================
-- ACTUALIZACIÓN AUTOMÁTICA DE updated_at
-- =========================================================

CREATE OR REPLACE FUNCTION agendaflow.set_updated_at()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$;

DO $$
DECLARE
    table_name_value TEXT;
BEGIN
    FOREACH table_name_value IN ARRAY ARRAY[
        'organizations',
        'branches',
        'app_users',
        'organization_memberships',
        'roles',
        'organization_contacts',
        'service_categories',
        'services',
        'specialists',
        'availability_schedules',
        'schedule_blocks',
        'resources',
        'customers',
        'appointments',
        'waitlist_requests',
        'notification_templates',
        'notifications'
    ]
    LOOP
        EXECUTE format(
            'CREATE TRIGGER %I BEFORE UPDATE ON agendaflow.%I
             FOR EACH ROW EXECUTE FUNCTION agendaflow.set_updated_at()',
            'trg_' || table_name_value || '_updated_at',
            table_name_value
        );
    END LOOP;
END;
$$;

-- =========================================================
-- PERMISOS Y ROLES INICIALES
-- =========================================================

INSERT INTO permissions (code, name, module, description)
VALUES
    ('ORGANIZATION_VIEW', 'Consultar organización', 'ORGANIZATION', 'Consultar configuración'),
    ('ORGANIZATION_UPDATE', 'Modificar organización', 'ORGANIZATION', 'Modificar configuración'),
    ('USERS_VIEW', 'Consultar usuarios', 'SECURITY', 'Consultar usuarios y membresías'),
    ('USERS_MANAGE', 'Administrar usuarios', 'SECURITY', 'Crear y modificar usuarios'),
    ('ROLES_VIEW', 'Consultar roles', 'SECURITY', 'Consultar roles y permisos'),
    ('ROLES_MANAGE', 'Administrar roles', 'SECURITY', 'Crear roles y asignar permisos'),
    ('BRANCHES_VIEW', 'Consultar sucursales', 'BRANCH', 'Consultar sucursales'),
    ('BRANCHES_MANAGE', 'Administrar sucursales', 'BRANCH', 'Crear y modificar sucursales'),
    ('CUSTOMERS_VIEW', 'Consultar clientes', 'CUSTOMER', 'Consultar clientes'),
    ('CUSTOMERS_CREATE', 'Crear clientes', 'CUSTOMER', 'Registrar clientes'),
    ('CUSTOMERS_UPDATE', 'Modificar clientes', 'CUSTOMER', 'Modificar clientes'),
    ('SERVICES_VIEW', 'Consultar servicios', 'SERVICE', 'Consultar servicios'),
    ('SERVICES_MANAGE', 'Administrar servicios', 'SERVICE', 'Crear y modificar servicios'),
    ('SPECIALISTS_VIEW', 'Consultar especialistas', 'SPECIALIST', 'Consultar especialistas'),
    ('SPECIALISTS_MANAGE', 'Administrar especialistas', 'SPECIALIST', 'Crear y modificar especialistas'),
    ('SCHEDULE_VIEW', 'Consultar horarios', 'SCHEDULE', 'Consultar disponibilidad'),
    ('SCHEDULE_MANAGE', 'Administrar horarios', 'SCHEDULE', 'Modificar disponibilidad'),
    ('APPOINTMENTS_VIEW', 'Consultar citas', 'APPOINTMENT', 'Consultar citas'),
    ('APPOINTMENTS_CREATE', 'Crear citas', 'APPOINTMENT', 'Crear citas'),
    ('APPOINTMENTS_UPDATE', 'Modificar citas', 'APPOINTMENT', 'Modificar o reprogramar citas'),
    ('APPOINTMENTS_CANCEL', 'Cancelar citas', 'APPOINTMENT', 'Cancelar citas'),
    ('APPOINTMENTS_COMPLETE', 'Completar citas', 'APPOINTMENT', 'Completar citas'),
    ('REPORTS_VIEW', 'Consultar reportes', 'REPORT', 'Consultar reportes'),
    ('AUDIT_VIEW', 'Consultar auditoría', 'AUDIT', 'Consultar eventos de auditoría')
ON CONFLICT (code) DO NOTHING;

INSERT INTO roles (organization_id, name, description, is_system_role)
VALUES
    (NULL, 'PLATFORM_ADMIN', 'Administrador global de la plataforma', TRUE),
    (NULL, 'ORGANIZATION_ADMIN', 'Administrador de una organización', TRUE),
    (NULL, 'MANAGER', 'Gerente o supervisor', TRUE),
    (NULL, 'RECEPTIONIST', 'Usuario de recepción', TRUE),
    (NULL, 'SPECIALIST', 'Prestador de servicios', TRUE),
    (NULL, 'AUDITOR', 'Usuario de consulta y auditoría', TRUE)
ON CONFLICT DO NOTHING;

INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id
FROM roles r
CROSS JOIN permissions p
WHERE r.name = 'ORGANIZATION_ADMIN'
  AND r.organization_id IS NULL
ON CONFLICT DO NOTHING;

INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id
FROM roles r
JOIN permissions p ON p.code IN (
    'ORGANIZATION_VIEW', 'USERS_VIEW', 'BRANCHES_VIEW',
    'CUSTOMERS_VIEW', 'CUSTOMERS_CREATE', 'CUSTOMERS_UPDATE',
    'SERVICES_VIEW', 'SPECIALISTS_VIEW', 'SCHEDULE_VIEW',
    'SCHEDULE_MANAGE', 'APPOINTMENTS_VIEW', 'APPOINTMENTS_CREATE',
    'APPOINTMENTS_UPDATE', 'APPOINTMENTS_CANCEL',
    'APPOINTMENTS_COMPLETE', 'REPORTS_VIEW'
)
WHERE r.name = 'MANAGER'
  AND r.organization_id IS NULL
ON CONFLICT DO NOTHING;

INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id
FROM roles r
JOIN permissions p ON p.code IN (
    'BRANCHES_VIEW', 'CUSTOMERS_VIEW', 'CUSTOMERS_CREATE',
    'CUSTOMERS_UPDATE', 'SERVICES_VIEW', 'SPECIALISTS_VIEW',
    'SCHEDULE_VIEW', 'APPOINTMENTS_VIEW', 'APPOINTMENTS_CREATE',
    'APPOINTMENTS_UPDATE', 'APPOINTMENTS_CANCEL'
)
WHERE r.name = 'RECEPTIONIST'
  AND r.organization_id IS NULL
ON CONFLICT DO NOTHING;

INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id
FROM roles r
JOIN permissions p ON p.code IN (
    'CUSTOMERS_VIEW', 'SERVICES_VIEW', 'SCHEDULE_VIEW',
    'SCHEDULE_MANAGE', 'APPOINTMENTS_VIEW',
    'APPOINTMENTS_UPDATE', 'APPOINTMENTS_COMPLETE'
)
WHERE r.name = 'SPECIALIST'
  AND r.organization_id IS NULL
ON CONFLICT DO NOTHING;

INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id
FROM roles r
JOIN permissions p ON p.code IN (
    'ORGANIZATION_VIEW', 'USERS_VIEW', 'ROLES_VIEW',
    'BRANCHES_VIEW', 'CUSTOMERS_VIEW', 'SERVICES_VIEW',
    'SPECIALISTS_VIEW', 'SCHEDULE_VIEW', 'APPOINTMENTS_VIEW',
    'REPORTS_VIEW', 'AUDIT_VIEW'
)
WHERE r.name = 'AUDITOR'
  AND r.organization_id IS NULL
ON CONFLICT DO NOTHING;
